package com.mboussetta.todoapp.ui.theme

// Color.kt
import androidx.compose.ui.graphics.Color


val todo_light_primary = Color(0xFF006496)
val todo_light_onPrimary = Color(0xFFFFFFFF)
val todo_light_primaryContainer = Color(0xFFCCE5FF)
val todo_light_onPrimaryContainer = Color(0xFF001E31)
val todo_light_secondary = Color(0xFF50606F)
val todo_light_onSecondary = Color(0xFFFFFFFF)
val todo_light_secondaryContainer = Color(0xFFD4E4F6)
val todo_light_onSecondaryContainer = Color(0xFF0D1D2A)
val todo_light_tertiary = Color(0xFF66587B)
val todo_light_onTertiary = Color(0xFFFFFFFF)
val todo_light_tertiaryContainer = Color(0xFFECDCFF)
val todo_light_onTertiaryContainer = Color(0xFF211534)
val todo_light_error = Color(0xFFBA1A1A)
val todo_light_errorContainer = Color(0xFFFFDAD6)
val todo_light_onError = Color(0xFFFFFFFF)
val todo_light_onErrorContainer = Color(0xFF410002)
val todo_light_background = Color(0xFFFCFCFF)
val todo_light_onBackground = Color(0xFF1A1C1E)
val todo_light_surface = Color(0xFFFCFCFF)
val todo_light_onSurface = Color(0xFF1A1C1E)
val todo_light_surfaceVariant = Color(0xFFDEE3EB)
val todo_light_onSurfaceVariant = Color(0xFF42474E)
val todo_light_outline = Color(0xFF72787E)
val todo_light_inverseOnSurface = Color(0xFFF0F0F4)
val todo_light_inverseSurface = Color(0xFF2F3133)
val todo_light_inversePrimary = Color(0xFF91CDFF)
val todo_light_surfaceTint = Color(0xFF006496)
val todo_light_outlineVariant = Color(0xFFC2C7CE)
val todo_light_scrim = Color(0xFF000000)

val todo_dark_primary = Color(0xFF91CDFF)
val todo_dark_onPrimary = Color(0xFF003350)
val todo_dark_primaryContainer = Color(0xFF004B72)
val todo_dark_onPrimaryContainer = Color(0xFFCCE5FF)
val todo_dark_secondary = Color(0xFFB8C8D9)
val todo_dark_onSecondary = Color(0xFF22323F)
val todo_dark_secondaryContainer = Color(0xFF394856)
val todo_dark_onSecondaryContainer = Color(0xFFD4E4F6)
val todo_dark_tertiary = Color(0xFFD1BFE7)
val todo_dark_onTertiary = Color(0xFF372A4A)
val todo_dark_tertiaryContainer = Color(0xFF4E4162)
val todo_dark_onTertiaryContainer = Color(0xFFECDCFF)
val todo_dark_error = Color(0xFFFFB4AB)
val todo_dark_errorContainer = Color(0xFF93000A)
val todo_dark_onError = Color(0xFF690005)
val todo_dark_onErrorContainer = Color(0xFFFFDAD6)
val todo_dark_background = Color(0xFF1A1C1E)
val todo_dark_onBackground = Color(0xFFE2E2E5)
val todo_dark_surface = Color(0xFF1A1C1E)
val todo_dark_onSurface = Color(0xFFE2E2E5)
val todo_dark_surfaceVariant = Color(0xFF42474E)
val todo_dark_onSurfaceVariant = Color(0xFFC2C7CE)
val todo_dark_outline = Color(0xFF8C9198)
val todo_dark_inverseOnSurface = Color(0xFF1A1C1E)
val todo_dark_inverseSurface = Color(0xFFE2E2E5)
val todo_dark_inversePrimary = Color(0xFF006496)
val todo_dark_surfaceTint = Color(0xFF91CDFF)
val todo_dark_outlineVariant = Color(0xFF42474E)
val todo_dark_scrim = Color(0xFF000000)
